package com.dao;

import android.content.Context;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Point;
import android.graphics.Rect;

import com.rect.SpeakingRect;

import java.util.ArrayList;
import java.util.List;

/**
 * Instantiating constructor must be called for 2 arg db storage
 * //TODO try to fix the explicit constructor call - may not be designed this way - paint
 * //TODO and rect are not persisted and the constructor needs to be called explicitly = force all fields to be persisted?
 */
public class RectDaoImpl {

    private  RectDatabase appDb;//TODo null checks? - only 1 for now

    public RectDaoImpl(Context context){
        appDb = (RectDatabase) RectDatabase.getInstance(context);
    }

    public List<SpeakingRect> getAllRects(){
        List<SpeakingRect> allRectsFromDB = appDb.rectDao().getAllRects();
        List<SpeakingRect> allRectsOfAPicResult = new ArrayList<>();
        for (SpeakingRect rect : allRectsFromDB){
            allRectsOfAPicResult.add(new SpeakingRect(rect.getId(),rect.getPicName(),rect.getRect(),rect.getPaint()));
        }
        return allRectsOfAPicResult;
    }

    /**
     * System.out.println("Alpha " + caters.get(0).getAlpha() + " Alpha from paint " +caters.get(0).getPaint().getAlpha() );
     * //TODO due to room persistence not able to hold objects, constructors that initialize default values must be called
     * @param picName
     * @return
     */
    public List<SpeakingRect> getAllRectsOfAPic(String picName){
        List<SpeakingRect> allRectsOfAPicFromDB = appDb.rectDao().getAllRectsOfAPic(picName);
        List<SpeakingRect> allRectsOfAPicResult = new ArrayList<>();
        for (SpeakingRect rect : allRectsOfAPicFromDB){
            allRectsOfAPicResult.add(new SpeakingRect(rect.getId(),rect.getPicName(),rect.getRect(),rect.getPaint()));
        }
        return allRectsOfAPicResult;

    }

    public SpeakingRect getRect(String picName, Rect rect){
        SpeakingRect rectResult = appDb.rectDao().getRect(picName, rect);//rect with 2 values filled //TODO not anymore //TODO maybe the explicit constructor call is no longer required?
        return new SpeakingRect(rectResult.getId(),rectResult.getPicName(),rectResult.getRect(),rectResult.getPaint());//rect with all values filled from the constructor //TODO not anymore
    }

    public void insertRect(String picName, Point point){ // id is autogenerated - pass 0 as not set
        if(picName != null){
            Paint paint = new Paint();//default paint
            paint.setStyle(Paint.Style.STROKE);//not inserted into db
            paint.setColor(Color.RED);
            paint.setStrokeWidth(3);
            paint.setAlpha(100);
            Rect rect = createRectfromPoint(point, 50);
            appDb.rectDao().insertRect(new SpeakingRect(0,picName,rect,paint));//call constructor for default values
        }
    }

    //TODO basic update only - picName and point
    public void updateRect(int id, String picName, Rect rect){
        appDb.rectDao().updateRect(id, picName, rect);
    }

    public void deleteAllRectsOfAPic(String picName){
        appDb.rectDao().deleteAllRectsOfAPic(picName);
    }

    public void deleteRect(String picName, Rect rect){
        appDb.rectDao().deleteRect(picName, rect);
    }

    public void deleteAll(){
        appDb.rectDao().deleteAll();
    }

    public Rect createRectfromPoint(Point point, int size){
        Rect rect = new Rect();
        rect.set (point.x - size, point.y - size, point.x + size, point.y +size);
        return rect;
    }






}
